before_install:
  - printenv
services:
  - docker
before_script: docker run --rm -v $(pwd):/app composer/composer install
script:
  - docker build -t reindexer-client .
  - docker run --rm -v $(pwd):/app reindexer-client ./vendor/bin/phpunit --coverage-clover=coverage_clover.xml --configuration=tests/ tests/