before_install:
  - printenv

matrix:
  include:
    - name: "7.1"
      env: PHP_VERSION=7.1
    - name: "7.2"
      env: PHP_VERSION=7.2
    - name: "7.3"
      env: PHP_VERSION=7.3

cache:
  directories:
    - $HOME/.composer

services:
  - docker

before_script:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - docker-compose build --build-arg PHP_VERSION=${PHP_VERSION}
  - export COMPOSE_FILE=docker-compose-tests.yml
  - docker-compose run --rm php composer install --no-interaction

script:
  - docker-compose run --rm php vendor/bin/phpunit
  - docker-compose run --rm php sh -c "vendor/bin/php-cs-fixer fix"
