before_install:
  - printenv
services:
  - docker
before_script:
  - docker pull composer
  - docker run --rm -v $(pwd):/app composer install
script:
  - docker build -t reindexer-client .
  - docker run --rm -v $(pwd):/app reindexer-client vendor/bin/phpunit
  - docker run --rm -v $(pwd):/app reindexer-client vendor/bin/php-cs-fixer style-fix