version: '3.6'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_MODE: debug
    volumes:
      - .:/var/www/html:cached
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
    depends_on:
      - reindexer
    networks: ['app-stack']
  nginx:
    image: wodby/nginx:latest
    ports:
      - 81:80
    depends_on:
      - php
    volumes:
      - .:/var/www/html:cached
    networks: ['app-stack']
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html
  reindexer:
    container_name: reindexer
    image: reindexer/reindexer
    volumes:
      - reindexer-data:/data
    ports:
      - 6534:6534
      - 9088:9088
    networks: ['app-stack']

volumes:
  reindexer-data:

networks:
    app-stack:

