version: '3.6'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    depends_on:
      - reindexer
    networks: ['app-stack']

  reindexer:
    image: reindexer/reindexer
    volumes:
      - reindexer-data:/data
    networks: ['app-stack']

volumes:
  reindexer-data:

networks: {app-stack:{}}

