<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>reindexer.grpc.DropIndexRequest</code>
 */
class DropIndexRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     */
    protected $dbName = '';
    /**
     * Generated from protobuf field <code>string nsName = 2;</code>
     */
    protected $nsName = '';
    /**
     * Generated from protobuf field <code>.reindexer.grpc.Index definition = 3;</code>
     */
    protected $definition = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbName
     *     @type string $nsName
     *     @type \Reindexer\Grpc\Index $definition
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nsName = 2;</code>
     * @return string
     */
    public function getNsName()
    {
        return $this->nsName;
    }

    /**
     * Generated from protobuf field <code>string nsName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNsName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nsName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.Index definition = 3;</code>
     * @return \Reindexer\Grpc\Index|null
     */
    public function getDefinition()
    {
        return $this->definition;
    }

    public function hasDefinition()
    {
        return isset($this->definition);
    }

    public function clearDefinition()
    {
        unset($this->definition);
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.Index definition = 3;</code>
     * @param \Reindexer\Grpc\Index $var
     * @return $this
     */
    public function setDefinition($var)
    {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\Index::class);
        $this->definition = $var;

        return $this;
    }

}

