<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Generated from protobuf message <code>reindexer.grpc.EnumDatabasesRequest</code>
 */
class EnumDatabasesRequest extends \Google\Protobuf\Internal\Message {
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }
}
