<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Index options
 *
 * Generated from protobuf message <code>reindexer.grpc.IndexOptions</code>
 */
class IndexOptions extends \Google\Protobuf\Internal\Message {
    /**
     * Generated from protobuf field <code>bool isPk = 1;</code>
     */
    protected $isPk = false;
    /**
     * Generated from protobuf field <code>bool isArray = 2;</code>
     */
    protected $isArray = false;
    /**
     * Generated from protobuf field <code>bool isDense = 3;</code>
     */
    protected $isDense = false;
    /**
     * Generated from protobuf field <code>bool isSparse = 4;</code>
     */
    protected $isSparse = false;
    /**
     * Generated from protobuf field <code>.reindexer.grpc.IndexOptions.RTreeType rtreeType = 5;</code>
     */
    protected $rtreeType = 0;
    /**
     * Generated from protobuf field <code>.reindexer.grpc.IndexOptions.CollateMode collateMode = 6;</code>
     */
    protected $collateMode = 0;
    /**
     * Generated from protobuf field <code>string sortOrdersTable = 7;</code>
     */
    protected $sortOrdersTable = '';
    /**
     * Generated from protobuf field <code>string config = 8;</code>
     */
    protected $config = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isPk
     *     @type bool $isArray
     *     @type bool $isDense
     *     @type bool $isSparse
     *     @type int $rtreeType
     *     @type int $collateMode
     *     @type string $sortOrdersTable
     *     @type string $config
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isPk = 1;</code>
     * @return bool
     */
    public function getIsPk() {
        return $this->isPk;
    }

    /**
     * Generated from protobuf field <code>bool isPk = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPk($var) {
        GPBUtil::checkBool($var);
        $this->isPk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isArray = 2;</code>
     * @return bool
     */
    public function getIsArray() {
        return $this->isArray;
    }

    /**
     * Generated from protobuf field <code>bool isArray = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsArray($var) {
        GPBUtil::checkBool($var);
        $this->isArray = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isDense = 3;</code>
     * @return bool
     */
    public function getIsDense() {
        return $this->isDense;
    }

    /**
     * Generated from protobuf field <code>bool isDense = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDense($var) {
        GPBUtil::checkBool($var);
        $this->isDense = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSparse = 4;</code>
     * @return bool
     */
    public function getIsSparse() {
        return $this->isSparse;
    }

    /**
     * Generated from protobuf field <code>bool isSparse = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSparse($var) {
        GPBUtil::checkBool($var);
        $this->isSparse = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.IndexOptions.RTreeType rtreeType = 5;</code>
     * @return int
     */
    public function getRtreeType() {
        return $this->rtreeType;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.IndexOptions.RTreeType rtreeType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setRtreeType($var) {
        GPBUtil::checkEnum($var, \Reindexer\Grpc\IndexOptions\RTreeType::class);
        $this->rtreeType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.IndexOptions.CollateMode collateMode = 6;</code>
     * @return int
     */
    public function getCollateMode() {
        return $this->collateMode;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.IndexOptions.CollateMode collateMode = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCollateMode($var) {
        GPBUtil::checkEnum($var, \Reindexer\Grpc\IndexOptions\CollateMode::class);
        $this->collateMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sortOrdersTable = 7;</code>
     * @return string
     */
    public function getSortOrdersTable() {
        return $this->sortOrdersTable;
    }

    /**
     * Generated from protobuf field <code>string sortOrdersTable = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSortOrdersTable($var) {
        GPBUtil::checkString($var, true);
        $this->sortOrdersTable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string config = 8;</code>
     * @return string
     */
    public function getConfig() {
        return $this->config;
    }

    /**
     * Generated from protobuf field <code>string config = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setConfig($var) {
        GPBUtil::checkString($var, true);
        $this->config = $var;

        return $this;
    }
}
