<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Metadata string
 *
 * Generated from protobuf message <code>reindexer.grpc.MetadataResponse</code>
 */
class MetadataResponse extends \Google\Protobuf\Internal\Message {
    /**
     * Generated from protobuf field <code>string metadata = 1;</code>
     */
    protected $metadata = '';
    /**
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 2;</code>
     */
    protected $errorResponse = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metadata
     *     @type \Reindexer\Grpc\ErrorResponse $errorResponse
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string metadata = 1;</code>
     * @return string
     */
    public function getMetadata() {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>string metadata = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var) {
        GPBUtil::checkString($var, true);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 2;</code>
     * @return \Reindexer\Grpc\ErrorResponse|null
     */
    public function getErrorResponse() {
        return $this->errorResponse;
    }

    public function hasErrorResponse() {
        return isset($this->errorResponse);
    }

    public function clearErrorResponse() {
        unset($this->errorResponse);
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 2;</code>
     * @param \Reindexer\Grpc\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var) {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\ErrorResponse::class);
        $this->errorResponse = $var;

        return $this;
    }
}
