<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Item definition.
 *
 * Generated from protobuf message <code>reindexer.grpc.ModifyItemRequest</code>
 */
class ModifyItemRequest extends \Google\Protobuf\Internal\Message {
    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     */
    protected $dbName = '';
    /**
     * Generated from protobuf field <code>string nsName = 2;</code>
     */
    protected $nsName = '';
    /**
     * Generated from protobuf field <code>.reindexer.grpc.ModifyMode mode = 3;</code>
     */
    protected $mode = 0;
    /**
     * Data in message should be encoded in one of the following formats:
     * 1.JSON
     * 2.CJSON
     * 3.MSGPACK
     * 4.PROTOBUF
     *
     * Generated from protobuf field <code>.reindexer.grpc.EncodingType encodingType = 4;</code>
     */
    protected $encodingType = 0;
    /**
     * Generated from protobuf field <code>bytes data = 5;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbName
     *     @type string $nsName
     *     @type int $mode
     *     @type int $encodingType
     *           Data in message should be encoded in one of the following formats:
     *           1.JSON
     *           2.CJSON
     *           3.MSGPACK
     *           4.PROTOBUF
     *     @type string $data
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @return string
     */
    public function getDbName() {
        return $this->dbName;
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var) {
        GPBUtil::checkString($var, true);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nsName = 2;</code>
     * @return string
     */
    public function getNsName() {
        return $this->nsName;
    }

    /**
     * Generated from protobuf field <code>string nsName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNsName($var) {
        GPBUtil::checkString($var, true);
        $this->nsName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.ModifyMode mode = 3;</code>
     * @return int
     */
    public function getMode() {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.ModifyMode mode = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var) {
        GPBUtil::checkEnum($var, \Reindexer\Grpc\ModifyMode::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * Data in message should be encoded in one of the following formats:
     * 1.JSON
     * 2.CJSON
     * 3.MSGPACK
     * 4.PROTOBUF
     *
     * Generated from protobuf field <code>.reindexer.grpc.EncodingType encodingType = 4;</code>
     * @return int
     */
    public function getEncodingType() {
        return $this->encodingType;
    }

    /**
     * Data in message should be encoded in one of the following formats:
     * 1.JSON
     * 2.CJSON
     * 3.MSGPACK
     * 4.PROTOBUF
     *
     * Generated from protobuf field <code>.reindexer.grpc.EncodingType encodingType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEncodingType($var) {
        GPBUtil::checkEnum($var, \Reindexer\Grpc\EncodingType::class);
        $this->encodingType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 5;</code>
     * @return string
     */
    public function getData() {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var) {
        GPBUtil::checkString($var, false);
        $this->data = $var;

        return $this;
    }
}
