<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>reindexer.grpc.OpenNamespaceRequest</code>
 */
class OpenNamespaceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     */
    protected $dbName = '';
    /**
     * Generated from protobuf field <code>.reindexer.grpc.StorageOptions storageOptions = 2;</code>
     */
    protected $storageOptions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbName
     *     @type \Reindexer\Grpc\StorageOptions $storageOptions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.StorageOptions storageOptions = 2;</code>
     * @return \Reindexer\Grpc\StorageOptions|null
     */
    public function getStorageOptions()
    {
        return $this->storageOptions;
    }

    public function hasStorageOptions()
    {
        return isset($this->storageOptions);
    }

    public function clearStorageOptions()
    {
        unset($this->storageOptions);
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.StorageOptions storageOptions = 2;</code>
     * @param \Reindexer\Grpc\StorageOptions $var
     * @return $this
     */
    public function setStorageOptions($var)
    {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\StorageOptions::class);
        $this->storageOptions = $var;

        return $this;
    }

}

