<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Namespaces definition.
 *
 * Generated from protobuf message <code>reindexer.grpc.Namespace</code>
 */
class PBNamespace extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     */
    protected $dbName = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.reindexer.grpc.StorageOptions storageOptions = 3;</code>
     */
    protected $storageOptions = null;
    /**
     * Generated from protobuf field <code>repeated .reindexer.grpc.Index indexesDefinitions = 4;</code>
     */
    private $indexesDefinitions;
    /**
     * Generated from protobuf field <code>bool isTemporary = 5;</code>
     */
    protected $isTemporary = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbName
     *     @type string $name
     *     @type \Reindexer\Grpc\StorageOptions $storageOptions
     *     @type array<\Reindexer\Grpc\Index>|\Google\Protobuf\Internal\RepeatedField $indexesDefinitions
     *     @type bool $isTemporary
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.StorageOptions storageOptions = 3;</code>
     * @return \Reindexer\Grpc\StorageOptions|null
     */
    public function getStorageOptions()
    {
        return $this->storageOptions;
    }

    public function hasStorageOptions()
    {
        return isset($this->storageOptions);
    }

    public function clearStorageOptions()
    {
        unset($this->storageOptions);
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.StorageOptions storageOptions = 3;</code>
     * @param \Reindexer\Grpc\StorageOptions $var
     * @return $this
     */
    public function setStorageOptions($var)
    {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\StorageOptions::class);
        $this->storageOptions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .reindexer.grpc.Index indexesDefinitions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexesDefinitions()
    {
        return $this->indexesDefinitions;
    }

    /**
     * Generated from protobuf field <code>repeated .reindexer.grpc.Index indexesDefinitions = 4;</code>
     * @param array<\Reindexer\Grpc\Index>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexesDefinitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Reindexer\Grpc\Index::class);
        $this->indexesDefinitions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isTemporary = 5;</code>
     * @return bool
     */
    public function getIsTemporary()
    {
        return $this->isTemporary;
    }

    /**
     * Generated from protobuf field <code>bool isTemporary = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTemporary($var)
    {
        GPBUtil::checkBool($var);
        $this->isTemporary = $var;

        return $this;
    }

}

