<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>reindexer.grpc.ProtobufSchemaResponse</code>
 */
class ProtobufSchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * text representation of .proto file
     *
     * Generated from protobuf field <code>string proto = 1;</code>
     */
    protected $proto = '';
    /**
     * error code
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 2;</code>
     */
    protected $errorResponse = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $proto
     *           text representation of .proto file
     *     @type \Reindexer\Grpc\ErrorResponse $errorResponse
     *           error code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * text representation of .proto file
     *
     * Generated from protobuf field <code>string proto = 1;</code>
     * @return string
     */
    public function getProto()
    {
        return $this->proto;
    }

    /**
     * text representation of .proto file
     *
     * Generated from protobuf field <code>string proto = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProto($var)
    {
        GPBUtil::checkString($var, True);
        $this->proto = $var;

        return $this;
    }

    /**
     * error code
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 2;</code>
     * @return \Reindexer\Grpc\ErrorResponse|null
     */
    public function getErrorResponse()
    {
        return $this->errorResponse;
    }

    public function hasErrorResponse()
    {
        return isset($this->errorResponse);
    }

    public function clearErrorResponse()
    {
        unset($this->errorResponse);
    }

    /**
     * error code
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 2;</code>
     * @param \Reindexer\Grpc\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var)
    {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\ErrorResponse::class);
        $this->errorResponse = $var;

        return $this;
    }

}

