<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Sets metadata by key,
 * field 'value' should contain metadata value.
 *
 * Generated from protobuf message <code>reindexer.grpc.PutMetaRequest</code>
 */
class PutMetaRequest extends \Google\Protobuf\Internal\Message {
    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     */
    protected $dbName = '';
    /**
     * Generated from protobuf field <code>.reindexer.grpc.Metadata metadata = 2;</code>
     */
    protected $metadata = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbName
     *     @type \Reindexer\Grpc\Metadata $metadata
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @return string
     */
    public function getDbName() {
        return $this->dbName;
    }

    /**
     * Generated from protobuf field <code>string dbName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var) {
        GPBUtil::checkString($var, true);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.Metadata metadata = 2;</code>
     * @return \Reindexer\Grpc\Metadata|null
     */
    public function getMetadata() {
        return $this->metadata;
    }

    public function hasMetadata() {
        return isset($this->metadata);
    }

    public function clearMetadata() {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>.reindexer.grpc.Metadata metadata = 2;</code>
     * @param \Reindexer\Grpc\Metadata $var
     * @return $this
     */
    public function setMetadata($var) {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\Metadata::class);
        $this->metadata = $var;

        return $this;
    }
}
