<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Query definition. Represents query
 * as a binary serialized buffer.
 *
 * Generated from protobuf message <code>reindexer.grpc.Query</code>
 */
class Query extends \Google\Protobuf\Internal\Message
{
    /**
     * Query can be encoded as following:
     * 1. JSON
     * 2. MSGPACK
     *
     * Generated from protobuf field <code>.reindexer.grpc.EncodingType encdoingType = 1;</code>
     */
    protected $encdoingType = 0;
    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $encdoingType
     *           Query can be encoded as following:
     *           1. JSON
     *           2. MSGPACK
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Query can be encoded as following:
     * 1. JSON
     * 2. MSGPACK
     *
     * Generated from protobuf field <code>.reindexer.grpc.EncodingType encdoingType = 1;</code>
     * @return int
     */
    public function getEncdoingType()
    {
        return $this->encdoingType;
    }

    /**
     * Query can be encoded as following:
     * 1. JSON
     * 2. MSGPACK
     *
     * Generated from protobuf field <code>.reindexer.grpc.EncodingType encdoingType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEncdoingType($var)
    {
        GPBUtil::checkEnum($var, \Reindexer\Grpc\EncodingType::class);
        $this->encdoingType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

