<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Query execution results set
 *
 * Generated from protobuf message <code>reindexer.grpc.QueryResultsResponse</code>
 */
class QueryResultsResponse extends \Google\Protobuf\Internal\Message {
    /**
     * Bytes stream.
     *
     * Generated from protobuf field <code>bytes data = 1;</code>
     */
    protected $data = '';
    /**
     * contains options only for the first item in a stream
     *
     * Generated from protobuf field <code>.reindexer.grpc.QueryResultsResponse.QueryResultsOptions options = 2;</code>
     */
    protected $options = null;
    /**
     * status
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 3;</code>
     */
    protected $errorResponse = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $data
     *           Bytes stream.
     *     @type \Reindexer\Grpc\QueryResultsResponse\QueryResultsOptions $options
     *           contains options only for the first item in a stream
     *     @type \Reindexer\Grpc\ErrorResponse $errorResponse
     *           status
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Bytes stream.
     *
     * Generated from protobuf field <code>bytes data = 1;</code>
     * @return string
     */
    public function getData() {
        return $this->data;
    }

    /**
     * Bytes stream.
     *
     * Generated from protobuf field <code>bytes data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var) {
        GPBUtil::checkString($var, false);
        $this->data = $var;

        return $this;
    }

    /**
     * contains options only for the first item in a stream
     *
     * Generated from protobuf field <code>.reindexer.grpc.QueryResultsResponse.QueryResultsOptions options = 2;</code>
     * @return \Reindexer\Grpc\QueryResultsResponse\QueryResultsOptions|null
     */
    public function getOptions() {
        return $this->options;
    }

    public function hasOptions() {
        return isset($this->options);
    }

    public function clearOptions() {
        unset($this->options);
    }

    /**
     * contains options only for the first item in a stream
     *
     * Generated from protobuf field <code>.reindexer.grpc.QueryResultsResponse.QueryResultsOptions options = 2;</code>
     * @param \Reindexer\Grpc\QueryResultsResponse\QueryResultsOptions $var
     * @return $this
     */
    public function setOptions($var) {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\QueryResultsResponse\QueryResultsOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * status
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 3;</code>
     * @return \Reindexer\Grpc\ErrorResponse|null
     */
    public function getErrorResponse() {
        return $this->errorResponse;
    }

    public function hasErrorResponse() {
        return isset($this->errorResponse);
    }

    public function clearErrorResponse() {
        unset($this->errorResponse);
    }

    /**
     * status
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse errorResponse = 3;</code>
     * @param \Reindexer\Grpc\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var) {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\ErrorResponse::class);
        $this->errorResponse = $var;

        return $this;
    }
}
