<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Transaction data.
 *
 * Generated from protobuf message <code>reindexer.grpc.TransactionIdResponse</code>
 */
class TransactionIdResponse extends \Google\Protobuf\Internal\Message {
    /**
     * Operation status
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse status = 1;</code>
     */
    protected $status = null;
    /**
     * unique transaction ID
     *
     * Generated from protobuf field <code>int64 id = 2;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Reindexer\Grpc\ErrorResponse $status
     *           Operation status
     *     @type int|string $id
     *           unique transaction ID
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Operation status
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse status = 1;</code>
     * @return \Reindexer\Grpc\ErrorResponse|null
     */
    public function getStatus() {
        return $this->status;
    }

    public function hasStatus() {
        return isset($this->status);
    }

    public function clearStatus() {
        unset($this->status);
    }

    /**
     * Operation status
     *
     * Generated from protobuf field <code>.reindexer.grpc.ErrorResponse status = 1;</code>
     * @param \Reindexer\Grpc\ErrorResponse $var
     * @return $this
     */
    public function setStatus($var) {
        GPBUtil::checkMessage($var, \Reindexer\Grpc\ErrorResponse::class);
        $this->status = $var;

        return $this;
    }

    /**
     * unique transaction ID
     *
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @return int|string
     */
    public function getId() {
        return $this->id;
    }

    /**
     * unique transaction ID
     *
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var) {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }
}
