<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reindexer.proto

namespace Reindexer\Grpc\QueryResultsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Options for returned buffer.
 *
 * Generated from protobuf message <code>reindexer.grpc.QueryResultsResponse.QueryResultsOptions</code>
 */
class QueryResultsOptions extends \Google\Protobuf\Internal\Message {
    /**
     * Generated from protobuf field <code>int64 totalItems = 1;</code>
     */
    protected $totalItems = 0;
    /**
     * Generated from protobuf field <code>int64 queryTotalItems = 2;</code>
     */
    protected $queryTotalItems = 0;
    /**
     * Generated from protobuf field <code>bool cacheEnabled = 3;</code>
     */
    protected $cacheEnabled = false;
    /**
     * Generated from protobuf field <code>string explain = 4;</code>
     */
    protected $explain = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $totalItems
     *     @type int|string $queryTotalItems
     *     @type bool $cacheEnabled
     *     @type string $explain
     * }
     */
    public function __construct($data = null) {
        \GPBMetadata\Reindexer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 totalItems = 1;</code>
     * @return int|string
     */
    public function getTotalItems() {
        return $this->totalItems;
    }

    /**
     * Generated from protobuf field <code>int64 totalItems = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalItems($var) {
        GPBUtil::checkInt64($var);
        $this->totalItems = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 queryTotalItems = 2;</code>
     * @return int|string
     */
    public function getQueryTotalItems() {
        return $this->queryTotalItems;
    }

    /**
     * Generated from protobuf field <code>int64 queryTotalItems = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQueryTotalItems($var) {
        GPBUtil::checkInt64($var);
        $this->queryTotalItems = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool cacheEnabled = 3;</code>
     * @return bool
     */
    public function getCacheEnabled() {
        return $this->cacheEnabled;
    }

    /**
     * Generated from protobuf field <code>bool cacheEnabled = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setCacheEnabled($var) {
        GPBUtil::checkBool($var);
        $this->cacheEnabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string explain = 4;</code>
     * @return string
     */
    public function getExplain() {
        return $this->explain;
    }

    /**
     * Generated from protobuf field <code>string explain = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExplain($var) {
        GPBUtil::checkString($var, true);
        $this->explain = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(QueryResultsOptions::class, \Reindexer\Grpc\QueryResultsResponse_QueryResultsOptions::class);
