name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:7.1-cli-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Show php version
      run: php -v && composer -V
    - name: Install dependencies
      run: composer install
    - name: Run unit tests
      run: vendor/bin/phpunit --testsuite "Reindexer Unit Test Suite"
    - name: Run style-fixer
      run: vendor/bin/php-cs-fixer fix --dry-run