name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
    services:
      reindexer:
        image: reindexer/reindexer
        ports:
          - 9088:9088
    steps:
    - uses: actions/checkout@v1
    - name: Show php version
      run: php${{ matrix.php }} -v && composer -V
    - name: Add reindxer to /etc/hosts
      run: echo '127.0.0.1 reindexer ' >> /etc/hosts
    - name: Install dependencies
      run: composer install
    - name: Run unit and integration tests
      run: php${{ matrix.php }} vendor/bin/phpunit
    - name: Run style-fixer
      run: php${{ matrix.php }} vendor/bin/php-cs-fixer fix --dry-run
