name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Show php version
      run: php -v
    - name: Run a multi-line script
      run: |
        composer -V
