name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    services:
      reindexer:
        image: reindexer/reindexer
        ports:
          - 9088:9088
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
    - name: Show php and composer version
      run: php -v && composer -V
    - name: Install dependencies
      run: composer install
    - name: Run unit and integration tests
      run: |
        mkdir -p build/logs
        php${{ matrix.php }} vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      env:
        REINDEXER_HOST: "http://0.0.0.0:9088"
    - name: Run style-fixer
      run: php${{ matrix.php }} vendor/bin/php-cs-fixer fix --dry-run
    - name: Code coverage
      run: php${{matrix.php}} vendor/bin/php-coveralls -v
      env:
        COVERALLS_RUN_LOCALLY: ${{secrets.COVERALLS_RUN_LOCALLY}}
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
