name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
    services:
      reindexer:
        image: reindexer/reindexer
        ports:
          - 9088:9088
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug
    - name: Show php and composer version
      run: php -v && composer -V
    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
    - name: Run unit and feature tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      env:
        REINDEXER_HOST: "http://127.0.0.1:9088"
    - name: Check code style
      run: vendor/bin/php-cs-fixer fix --dry-run --diff
      env:
        PHP_CS_FIXER_IGNORE_ENV: 1
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.xml
        verbose: true
