name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
    services:
      reindexer:
        image: reindexer/reindexer
        ports:
          - 9088:9088
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug
    - name: Show php and composer version
      run: php -v && composer -V
    - name: debug if needed
      run: if [[ "$DEBUG" == "true" ]]; then env; fi
      env:
        DEBUG: ${{secrets.DEBUG}}
    - name: Update phpunit for compability PHP 8
      if: (startsWith(matrix.php, '8.0'))
      run: |
        composer require phpunit/phpunit:9.5
    - name: Install dependencies
      run: composer install
    - name: Run unit and integration tests
      run: |
        php vendor/bin/phpunit --coverage-clover=coverage.xml
      env:
        REINDEXER_HOST: "http://0.0.0.0:9088"
    - name: "Upload coverage file"
      uses: "actions/upload-artifact@v2"
      with:
        name: "phpunit-${{ matrix.deps }}-${{ matrix.php-version }}.coverage"
        path: "coverage.xml"
    - name: Run style-fixer
      run: php vendor/bin/php-cs-fixer fix --dry-run
    - name: "Download coverage files"
      uses: "actions/download-artifact@v2"
      with:
        path: "reports"
    - uses: codecov/codecov-action@v2
      with:
        directory: "reports"
        verbose: true # optional (default = false)
